### PR TITLE
Update messages.json V3 (fr) version

### PR DESCRIPTION
**Pull request by Need74**
Hi

just a little harmonization between the order of the elements between Github and Transifex.

PS: I updated the translation on Transifex from the new "message.json" version (en) file but I don't know if I should create the "message.json" version (fr) file from the "for_use_gmail-notifier-addon_messagesjson-v3_fr_FR.json" file that I downloaded from Transifex, by adding the missing lines and characters to have the format used on Github. I hope I am clear in my question, namely do you want me to update the Github file with the latest version or do you prefer to do it yourself?

### CODE REVIEW

**Comment by inbasic** [comment]
I've just updated both "fr" and "it" locales from Transifex. Please take a look.

> by adding the missing lines and characters to have the format used on Github.

Transifex has a "Download for use" button, which I use without making any changes to the JSON files. These files are not intended for modification, as I always update the locales directly from Transifex before releasing a new version.

**Comment by Need74** [comment]
> I've just updated both "fr" and "it" locales from Transifex. Please take a look.
> 
> > by adding the missing lines and characters to have the format used on Github.
> 
> Transifex has a "Download for use" button, which I use without making any changes to the JSON files. These files are not intended for modification, as I always update the locales directly from Transifex before releasing a new version.

Hi
OK I understand that it is only at the time of a new version that you transfer the Transifex files to Github.
So I have to wait for the new version so that the Github files are up to date again.
Regards

**Comment by inbasic** [comment]
Right, you can also ping me to merge from Transifex if you needed.

**Comment by Need74** [comment]
Hi,
I tried to merge the Transifex translation (fr) but I have a conflict in my PR
So I have done a new PR and have merge Transifex content
If this new PR is wrong you will have to merge the Transifex content on Github
Regards

**Comment by Need74** [comment]
> Right, you can also ping me to merge from Transifex if you needed.

Hi,
I tried to merge the Transifex translation (fr) but I have a conflict in my PR
So I have done a new PR and have merge Transifex content
If this new PR is wrong you will have to merge the Transifex content on Github
Regards

**Comment by inbasic** [comment]
There is no need to ask for merge. Just ping me and I'll push the latest version on Transifex

**Comment by Need74** [comment]
> There is no need to ask for merge. Just ping me and I'll push the latest version on Transifex

Hi,
Ok, I understood that I don't have to do anything on my side to merge and that I just have to "ping" you but is there a button or a function to "ping" on github or is there just a simple message at the end of the PR to formulate?

**Comment by inbasic** [comment]
I am releasing the new version based on the locales on Transifex.

>  a simple message at the end of the PR to formulate?

I typically merge from Transifex before releasing a new version. However, if you need to review it beforehand, feel free to do so.

**Comment by Need74** [comment]
Hello

Thanks for this information and I will update Transifex this evening with some minor things.
I am also finalizing the index.htm and index.css files for small presentation changes (size and positions for one or two choice lists) and I will make a PR but these changes are not fundamental to delay the release of the new version.

Kind regards

**Pull request closed without merging**
